version: '3.9'
services:
  app:
    build: .
    command:  npm run start
    environment:
      NODE_ENV: development
      JWT_SECRET: chavesecreta
      PORT: 3002
      MAILTRAP_HOST: sandbox.smtp.mailtrap.io
      MAILTRAP_USER: SEU USUÁRIO
      MAILTRAP_PASSWORD: SUA SENHA
      MAILTRAP_MAIL: SEU EMAIL
      REDIS_HOST: redis
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "3002:3002"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "5432:5432"
